
const CHANGE_FORMULA_EDITOR_FOCUS = 'CHANGE_FORMULA_EDITOR_FOCUS';
const GET_FORMULA_EDITOR_STYLE = 'GET_FORMULA_EDITOR_STYLE';
const CHANGE_FORMULA_EDITOR_BUTTON_STATE = 'CHANGE_FORMULA_EDITOR_BUTTON_STATE';
const CHANGE_SYMBOL_POPOVER_STATE = 'CHANGE_SYMBOL_POPOVER_STATE';
const CHANGE_EMOJI_POPOVER_STATE = 'CHANGE_EMOJI_POPOVER_STATE';

export {CHANGE_FORMULA_EDITOR_FOCUS, GET_FORMULA_EDITOR_STYLE, CHANGE_FORMULA_EDITOR_BUTTON_STATE, CHANGE_SYMBOL_POPOVER_STATE, CHANGE_EMOJI_POPOVER_STATE};